# Generated by Django 2.1 on 2018-08-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('1', '初级'), ('2', '中级'), ('3', '高级')], default='1', max_length=50, verbose_name='课程等级'),
        ),
    ]
